### ISSUE TITLE
Some feature requests

### ISSUE THREAD

**Issue by Auuki** [grondag/darkness#12]
Hey, just wanted to ask for some features to be added:

1. A config option so when the mod is on the server and the option is turned on, everyone without the mod is applied with Blindness debuff (or any idea that would help with "promoting" the mod usage).
2. Option to set the darkness level so it's not just vanilla or pure darkness.
3. Option to set darkness level for each moon phase. Idea is to make it progressive between full moon and new moon.
4. Compatibility with [Enhanced Celestials](https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials) mod to allow custom darkness levels based on the event.

If darkness levels cannot be done for technical reasons then I'd like to ask for an explanation on how the mod works exactly out of curiosity to understand where the limitation stems from.

**Comment by grondag** [comment]
There are some configuration options for darkness levels already - not sure what more is desired.

This mod works by modifying the light map texture used by the renderer.  The texture and the associated calculations only run on the client, which is why a server-side version of the mod isn't practical.

Forcing or encouraging clients to run a mod from the server presents a host of challenges beyond the scope of this mod, and could always be circumvented by a determined actor.
